### ISSUE TITLE
Create a Contribuing.md

### ISSUE THREAD

**Issue by brunoromeiro** [brunoromeiro/hacktoberfest2020#3]
Create a simple Contribuing.md

**Comment by SambhavBhurtel** [comment]
Hi @brunoromeiro please assign me with this. I would like to contribute.

**Comment by brunoromeiro** [comment]
@SambhavBhurtel go!

**Comment by SambhavBhurtel** [comment]
Hi @brunoromeiro. For some reason, hacktoberfest is showing this repo as invalid. It's suggesting that the maintainer should add "hacktoberfest" topic to the repo if they want to participate. Can you add hacktoberfest as the topic for this repo? Thanks!

**Comment by brunoromeiro** [comment]
@SambhavBhurtel Excuse! Check now if everything is okay, please?

**Comment by SambhavBhurtel** [comment]
@brunoromeiro Everything's okay now. Thanks!
